// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh_bRznEJ6faIDQ5-JLt5SRBCiTXtuyI8',
    appId: '1:223243100486:android:2e116bee927250a60b4547',
    messagingSenderId: '223243100486',
    projectId: 'mais-receitas-9e2e3',
    storageBucket: 'mais-receitas-9e2e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnNStLQKACWfhc0c1z8ckm-cTB7XgHtdg',
    appId: '1:223243100486:ios:471f6c496bac11360b4547',
    messagingSenderId: '223243100486',
    projectId: 'mais-receitas-9e2e3',
    storageBucket: 'mais-receitas-9e2e3.appspot.com',
    iosClientId: '223243100486-r68ourcm70oe6ktcri5m54s7afbn426j.apps.googleusercontent.com',
    iosBundleId: 'com.example.maisReceitas',
  );
}
